# syntax=docker/dockerfile:1
FROM ardupilot/ardupilot-dev-base:latest

RUN apt-get update && apt-get install --no-install-recommends -y \
    lcov \
    gcovr \
    && apt-get clean \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
