# syntax=docker/dockerfile:1
ARG TAG="latest"
FROM ardupilot/ardupilot-dev-coverage:${TAG}

RUN apt-get update && dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
    gcc-multilib \
    g++-multilib \
    can-utils \
    iproute2 \
    && apt-get clean \
	&& apt-get -y autoremove \
	&& apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
