FROM khancyr/ardupilot-dev-chibios

# Bloaty install
RUN git clone --recursive https://github.com/google/bloaty.git /tmp/bloaty \
    && cd /tmp/bloaty \
    && cmake -GNinja . \
    && ninja -j $(nproc) bloaty \
    && cp bloaty /usr/local/bin/ \
    && cd \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

