FROM ardupilot/ardupilot-dev-base

RUN apt-get update && apt-get install --no-install-recommends -y \
    g++-aarch64-linux-gnu \
    gcc-aarch64-linux-gnu \
    pkg-config-aarch64-linux-gnu \
    && apt-get clean \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
