FROM ardupilot/ardupilot-dev-base

RUN apt-get update && apt-get install --no-install-recommends -y \
    g++-arm-linux-gnueabihf \
    pkg-config \
    && apt-get clean \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
