# syntax=docker/dockerfile:1
ARG TAG="latest"
FROM ardupilot/ardupilot-dev-base:${TAG}

RUN apt-get update && apt-get install --no-install-recommends -y \
    lcov \
    gcovr \
    && apt-get clean \
	&& apt-get -y autoremove \
	&& apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
