FROM khancyr/ardupilot-dev-base

# Get STM32 GCC9 toolchain
ARG ARM_ROOT="gcc-arm-none-eabi-9-2020-q2-update"
ARG ARM_TARBALL="$ARM_ROOT-x86_64-linux.tar.bz2"
ARG ARM_TARBALL_URL="https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/$ARM_TARBALL"

RUN mkdir -p /opt && cd /opt \
	&& wget -qO- "$ARM_TARBALL_URL" | tar jx \
	&& rm -rf "/opt/$ARM_ROOT/share/doc"

# manual ccache setup for arm-none-eabi-g++/arm-none-eabi-gcc
RUN ln -s /usr/bin/ccache /usr/lib/ccache/arm-none-eabi-g++ \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/arm-none-eabi-gcc

# Set STM32 toolchain to the PATH
ENV PATH="/opt/$ARM_ROOT/bin:$PATH"

# Set ccache to the PATH
ENV PATH="/usr/lib/ccache:$PATH"
