# syntax=docker/dockerfile:1
FROM ardupilot/ardupilot-dev-chibios:latest

RUN apt-get update && apt-get install --no-install-recommends -y \
    clang-14 \
    llvm-14 \
    && apt-get clean \
    && apt-get -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# symlink to compiler versions
RUN ln -s /usr/bin/clang-14 /usr/bin/clang \
    && ln -s /usr/bin/clang++-14 /usr/bin/clang++

# configure ccache
RUN ln -s /usr/bin/ccache /usr/lib/ccache/clang \
    && ln -s /usr/bin/ccache /usr/lib/ccache/clang++
