# syntax=docker/dockerfile:1
ARG TAG="latest"
FROM ardupilot/ardupilot-dev-base:${TAG}
ENV CLANG_VERSION=14

RUN apt-get update && apt-get install --no-install-recommends -y \
    clang-"$CLANG_VERSION" \
    llvm-"$CLANG_VERSION" \
    && apt-get clean \
    && apt-get -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# symlink to compiler versions
RUN ln -s /usr/bin/clang-"$CLANG_VERSION" /usr/bin/clang \
    && ln -s /usr/bin/clang++-"$CLANG_VERSION" /usr/bin/clang++

# configure ccache
RUN ln -s /usr/bin/ccache /usr/lib/ccache/clang \
    && ln -s /usr/bin/ccache /usr/lib/ccache/clang++
