name: build and push ArduPilot container

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # git checkout the PR
      - uses: actions/checkout@v2

      # Only push if it comes from tagging
      - name: Build ardupilot-dev-base images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: khancyr/ardupilot_dev
          tags: latest
          tag_with_ref: true
          add_git_labels: true
          path: docker
          dockerfile: docker/Dockerfile_dev-base
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
